remote_theme: pmarsceill/just-the-docs
logo: "img/xbackbone.png"
title: "XBackBone"
aux_links:
  "XBackBone on GitHub":
    - "//github.com/SergiX44/XBackBone"
footer_content: "Copyright &copy; 2020 Patrick Marsceill. Distributed by an <a href=\"https://github.com/SergiX44/XBackBone/blob/master/LICENSE\">AGPL v3.0 license.</a>"